//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WPR_UTILITIES.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WPR_UTILITIES_DIALOG        102
#define IDS_STRING1                     102
#define IDS_STRING2                     103
#define IDS_STRING3                     104
#define IDS_STRING4                     105
#define IDS_STRING5                     106
#define IDD_PF_SYS_AND_PA               107
#define IDS_STRING6                     107
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDR_WP_CSTYPE                   129
#define IDB_BK                          130
#define IDD_LOGODIALOG                  131
#define IDD_PARAM_DIAG_SPEC             134
#define IDD_PLAYBACK                    135
#define IDD_PLAYBACKIQDATA              135
#define IDD_PARAM_COMM                  136
#define IDD_PARAM_AL_LIMIT              137
#define IDD_PARAM_GRD_CLUT              138
#define IDD_PASSWORD                    139
#define IDD_PARAM_RASS_GRD_CLUT         140
#define IDD_PARAM_CTRL_WORD             141
#define IDD_PARAM_SITE                  142
#define IDR_MAINFRAME1                  142
#define IDD_PARAM_VEL_CON               143
#define IDD_PARAM_OTHER                 144
#define IDD_DOPTEST_PARAM               145
#define IDR_TOOLBAR                     146
#define IDD_PARAM_CALIBRATION           146
#define IDI_ICON1                       148
#define IDD_COMM_IP_SET_DIALOG          148
#define IDI_ICON2                       149
#define IDI_ICON3                       150
#define IDD_ARCHIVEA                    150
#define IDD_ARCHIVE_6MIN                150
#define IDI_ICON4                       151
#define IDD_PF_DRV_AND_FANS             151
#define IDI_ICON5                       152
#define IDD_PF_PWR_SUP                  152
#define IDI_ICON6                       153
#define IDD_PF_SUNDRIES_1               153
#define IDI_ICON7                       154
#define IDD_PF_HPA_AND_PA_TEMP          154
#define IDD_PF_SUNDRIES_2               155
#define IDD_BASIC_SETTING_DLG           156
#define IDD_PF_CALIBRATION              156
#define IDD_PLAYBACK6MINDATA            157
#define IDD_ARCHIVE_IQ                  158
#define IDD_DIALOG1                     158
#define IDD_NORMALSETTINGDLG            159
#define IDD_ADVANCEDSETTING_DLG         166
#define IDI_ICON8                       168
#define IDI_ICON9                       169
#define IDI_ICON10                      170
#define IDI_ICON11                      171
#define IDD_DMA_SETTING                 172
#define IDI_ICON12                      178
#define IDI_ICON13                      179
#define IDD_ALARMSETTING_DIALOG         180
#define IDD_ALARMSHOW                   181
#define IDD_DIALOG_SM                   186
#define IDD_DIALOG_UPS_STATUS           187
#define IDI_EAST                        198
#define IDI_NORTH                       199
#define IDI_SOUTH                       200
#define IDI_WEST                        201
#define IDI_VIRTICAL                    204
#define IDI_WEST_SELECTED               205
#define IDI_SOUTH_SELECTED              206
#define IDI_VIRTICAL_SELECTED           207
#define IDI_EAST_SELECTED               209
#define IDI_NORTH_SELECTED              210
#define IDI_ICON17                      211
#define ID_INDICATOR_INFORMATION        211
#define IDI_ICON14                      212
#define IDI_ICON15                      213
#define IDI_ICON16                      214
#define IDD_DIALOG_SM_MODIFIED          215
#define IDD_DIALOG_TIME_SERIES          218
#define IDD_DIALOG_BEAMSETTING          232
#define IDD_DIALOG_DATAVIEW             238
#define IDD_DIALOG_FREQ                 240
#define IDD_DIALOG_RAW                  241
#define IDD_DIALOG_DSP                  242
#define IDI_ICON18                      243
#define IDD_DIALOG_SPEC_VIEW            246
#define IDI_ICON19                      253
#define IDC_TEST_BEAM_NUM               1000
#define IDC_RASS_CUR_DATA_COMBO         1000
#define IDC_TST_BEAM_NUM                1000
#define IDC_SHOW                        1001
#define IDC_BEAM_NUM                    1001
#define IDC_TEST_SUBMODE                1001
#define IDC_RASS_CONTROL_TREE           1001
#define IDC_IMAGE1                      1002
#define IDC_SPEC_TYPE                   1002
#define IDC_TEST_FREQ                   1002
#define IDC_TST_RF_FREQ                 1002
#define IDC_SCAN_TYPE                   1003
#define IDC_TEST_ATTEN                  1003
#define IDC_RADIO2                      1003
#define IDC_ARCH_DISABLE                1003
#define IDC_TST_SIGNAL_AMP              1003
#define IDC_6MINARCH_DISABLE            1003
#define IDC_PATHNONE                    1003
#define IDC_NORMAL                      1003
#define IDC_ALARM_LIST                  1004
#define IDC_RANGE_GATE                  1004
#define IDC_TEST_DOP_FREQ               1004
#define IDC_RADIO3                      1004
#define IDC_ARCH_ENABLE                 1004
#define IDC_HIRANGE_GATE                1004
#define IDC_TST_DOP_PHASE               1004
#define IDC_6MINARCH_ENABLE             1004
#define IDC_HIGH                        1004
#define IDC_EDIT1                       1005
#define IDC_PRF_VER_HIGH                1005
#define IDC_LORANGE_GATE                1005
#define IDC_MODE_EDIT                   1005
#define IDC_TST_COAX_SWITCH             1005
#define IDC_PRF_VH                      1005
#define IDC_METEOR_PARAM                1005
#define IDC_IP_ADDR_EDIT                1005
#define IDC_PORT                        1005
#define IDC_LOWMODE_DMA                 1005
#define IDC_MINVALUE                    1005
#define IDC_CURRENTTIME                 1005
#define IDC_SWEEP_NUM                   1005
#define IDC_HIGHMODE_STARTGATE          1005
#define IDC_EDIT_Tx5v                   1005
#define IDC_EDIT_UPS                    1005
#define IDC_EDIT_IP_VOLTAGE             1005
#define IDC_EDIT_PHASE_NOISE_DB         1005
#define IDC_EDIT_MARKER                 1005
#define IDC_EDIT_CENTER_FREQ            1005
#define IDC_EDIT_NORMAL_NUM             1005
#define IDC_EDIT2                       1006
#define IDC_CURPLAY_PATH                1006
#define IDC_SAMP_VER_HIGH               1006
#define IDC_SYS15V_LIMIT                1006
#define IDC_STAT_EDIT                   1006
#define IDC_TST_SIGNAL_SOURCE           1006
#define IDC_TDASAMPLE_VH                1006
#define IDC_PT_CAL                      1006
#define IDC_6MINCURPLAY_PATH            1006
#define IDC_REMOTE_LINE_EDIT            1006
#define IDC_IP3                         1006
#define IDC_HIGHMODE_DMA                1006
#define IDC_MAXVALUE                    1006
#define IDC_LOWMODE_STARTGATE           1006
#define IDC_EDIT_Tx13v                  1006
#define IDC_EDIT_IP_FAULT_VOLTAGE       1006
#define IDC_EDIT_PHASE_NOISE_DEG        1006
#define IDC_EDIT_VELOCITY               1006
#define IDC_EDIT_SAMPLE_CLOCK           1006
#define IDC_EDIT_ERROR_NUM              1006
#define IDC_EDIT_BYTE_READ_SM           1006
#define IDC_EDIT3                       1007
#define IDC_PLAY_PATH                   1007
#define IDC_SPEC_VER_HIGH               1007
#define IDC_SYS5V_LIMIT                 1007
#define IDC_STATUS_EDIT                 1007
#define IDC_SDASAMPLE_VH                1007
#define IDC_ANT_HORBMWID                1007
#define IDC_ARCHIVEIQ_PATH              1007
#define IDC_IP2                         1007
#define IDC_EDIT_Tx50v                  1007
#define IDC_EDIT_OP_VOLTAGE             1007
#define IDC_EDIT_VIRTICAL               1007
#define IDC_EDIT_POWER_AVG              1007
#define IDC_EDIT_RFGATE                 1007
#define IDC_EDIT_BYTE_READ_UPS          1007
#define IDC_EDIT4                       1008
#define IDC_ARCH_PATH                   1008
#define IDC_TIME_VER_HIGH               1008
#define IDC_SYS28V_LIMIT                1008
#define IDC_ARCHA_EDIT                  1008
#define IDC_TST_NOISE_SOURCE            1008
#define IDC_ARCH6MIN_PATH               1008
#define IDC_IP1                         1008
#define IDC_EDIT_Tx28v                  1008
#define IDC_EDIT_IP_FREQUENCE           1008
#define IDC_EDIT_WEST                   1008
#define IDC_EDIT_PHASE_AVG              1008
#define IDC_EDIT_RFGATE_L               1008
#define IDC_EDIT_SYSINFO                1008
#define IDC_EDIT5                       1009
#define IDC_START_BUTTON                1009
#define IDC_PRF_VER_LOW                 1009
#define IDC_SYS6V_LIMIT                 1009
#define IDC_XMIT_EDIT                   1009
#define IDC_TST_SIGNAL_OUTPUT           1009
#define IDC_PRF_VL                      1009
#define IDC_IQSTART_BUTTON              1009
#define IDC_IP0                         1009
#define IDC_EDIT_Tx36v                  1009
#define IDC_EDIT_OP_LOAD                1009
#define IDC_EDIT_SOUTH                  1009
#define IDC_EDIT_PHASE_MM               1009
#define IDC_EDIT_BEGINGGATE_H           1009
#define IDC_CONTROL_TREE                1010
#define IDC_EDIT6                       1010
#define IDC_DRV_A_SP_STATUS_EDIT        1010
#define IDC_END_BUTTON                  1010
#define IDC_SAMP_VER_LOW                1010
#define IDC_AVG_PWR_EDIT                1010
#define IDC_TST_SM_RESET                1010
#define IDC_TDASAMPLE_VL                1010
#define IDC_IQEND_BUTTON                1010
#define IDC_ARCHIVEPATH                 1010
#define IDC_EDIT_Tx15v                  1010
#define IDC_EDIT_BATTERY_VOLTAGE        1010
#define IDC_EDIT_PWR_MM                 1010
#define IDC_EDIT_BEGINGATE_L            1010
#define IDC_PHA0                        1011
#define IDC_EDIT7                       1011
#define IDC_SPEC_VER_LOW                1011
#define IDC_MIN_OUTLET                  1011
#define IDC_CTL_EDIT                    1011
#define IDC_TST_LO_PHASE                1011
#define IDC_SDASAMPLE_VL                1011
#define IDC_PORT2                       1011
#define IDC_EDIT_Txm15v                 1011
#define IDC_EDIT_TEMPERATURE            1011
#define IDC_EDIT_POWER_SUM              1011
#define IDC_PHA1                        1012
#define IDC_CUR_DATA_COMBO              1012
#define IDC_EDIT8                       1012
#define IDC_TIME_VER_LOW                1012
#define IDC_MAX_OUTLET                  1012
#define IDC_RCVRSP_EDIT                 1012
#define IDC_TST_TRANSMITTER             1012
#define IDC_CW_EDIT                     1012
#define IDC_EDIT_PWR_VARIANCE           1012
#define IDC_PHA2                        1013
#define IDC_PASSWORD                    1013
#define IDC_EDIT9                       1013
#define IDC_PRF_OBL_HIGH                1013
#define IDC_MIN_INLET                   1013
#define IDC_LINK1_EDIT                  1013
#define IDC_PRF_OH                      1013
#define IDC_VELOCITY1_EDIT              1013
#define IDC_PHA3                        1014
#define IDC_GRCLUTR_STATIC              1014
#define IDC_PS_40V_SAMPLE_EDIT          1014
#define IDC_SAMP_OBL_HIGH               1014
#define IDC_MAX_INLET                   1014
#define IDC_LINK2_EDIT                  1014
#define IDC_TDASAMPLE_OH                1014
#define IDC_WIDTH1_EDIT                 1014
#define IDC_DP_TEST_CTRL                1014
#define IDC_PHA4                        1015
#define IDC_COMM_METHOD                 1015
#define IDC_PS_28V_SAMPLE_EDIT          1015
#define IDC_SPEC_OBL_HIGH               1015
#define IDC_MIN_PAMTEMP                 1015
#define IDC_TST_BM_DIRCHANGE            1015
#define IDC_SDASAMPLE_OH                1015
#define IDC_NOISE_EDIT                  1015
#define IDC_IQDIRBUTTON                 1015
#define IDC_PHA5                        1016
#define IDC_GOES_ID                     1016
#define IDC_MIN_SAMPLE_NUM              1016
#define IDC_MODULIDC_DRV_B_SP_STATUS_EDIT 1016
#define IDC_6V2p5_PS_SAMPLE_EDIT        1016
#define IDC_TIME_OBL_HIGH               1016
#define IDC_MAX_PAMTEMP                 1016
#define IDC_TST_BM_DIRECTION            1016
#define IDC_NOISE_TEMPERATURE           1016
#define IDC_LINE_NUM_COMBO              1016
#define IDC_6MINDIRBUTTON               1016
#define IDC_PHA6                        1017
#define IDC_GOES_CHANNUM                1017
#define IDC_RASS_CLUT_STATIC            1017
#define IDC_DRV_B_STATUS_EDIT           1017
#define IDC_6V3A_PS_SAMPLE_EDIT         1017
#define IDC_PRF_OBL_LOW                 1017
#define IDC_MIN_PADTEMP                 1017
#define IDC_PRF_OL                      1017
#define IDC_UNFILTEREDPOWER_EDIT        1017
#define IDC_6MINSTART_BUTTON            1017
#define IDC_GOES_TRAN_MIN               1018
#define IDC_DRV_A_STATUS_EDIT           1018
#define IDC_5VDIGITAL_PS_SAMPLE_EDIT    1018
#define IDC_SAMP_OBL_LOW                1018
#define IDC_MAX_PADTEMP                 1018
#define IDC_TST_RF_ATTEN                1018
#define IDC_TDASAMPLE_OL                1018
#define IDC_FILTEREDPOWER_EDIT          1018
#define IDC_6MINEND_BUTTON              1018
#define IDC_PHA7                        1019
#define IDC_GOES_TRAN_FREQ              1019
#define IDC_FAN1_EDIT                   1019
#define IDC_28V_PS_SAMPLE_EDIT          1019
#define IDC_SPEC_OBL_LOW                1019
#define IDC_MIN_INSIDE                  1019
#define IDC_SDASAMPLE_OL                1019
#define IDC_CLUTRSUP_EDIT               1019
#define IDC_IQCURPLAY_PATH              1019
#define IDC_TST_RF_GATEMOVING           1019
#define IDC_PHA8                        1020
#define IDC_RASS_CUR_DATA_EDIT          1020
#define IDC_M5V_PS_SAMPLE_EDIT          1020
#define IDC_TIME_OBL_LOW                1020
#define IDC_MAX_INSIDE                  1020
#define IDC_SYSCAL_EDIT                 1020
#define IDC_IQCURARCH_PATH              1020
#define IDC_TST_SAMPLELOC               1020
#define IDC_PHA9                        1021
#define IDC_SITE_LONGITUDE              1021
#define IDC_M15V_PS_SAMPLE_EDIT         1021
#define IDC_FFT_POINTS                  1021
#define IDC_MIN_OUTSIDE                 1021
#define IDC_FFT_POINT                   1021
#define IDC_CW_EX_EDIT                  1021
#define IDC_IQARCH_ENABLE               1021
#define IDC_TST_DIF_GATEMOVING          1021
#define IDC_SITE_LATITUDE               1022
#define IDC_15V_PS_SAMPLE_EDIT          1022
#define IDC_INT_CHECK_GATE              1022
#define IDC_MAX_OUTSIDE                 1022
#define IDC_IQARCH_DISABLE              1022
#define IDC_CW_EX_EDIT2                 1022
#define IDC_VEL_EX_EDIT1                1022
#define IDC_TST_PCCODEMOVING            1022
#define IDC_SITE_NAME                   1023
#define IDC_5V_PS_SAMPLE_EDIT           1023
#define IDC_CHECK_GATE                  1023
#define IDC_SYSCAL_LIMIT                1023
#define IDC_CW_EX_EDIT3                 1023
#define IDC_VEL_EDIT1                   1023
#define IDC_DRIVER_A                    1024
#define IDC_SITE_ELEVATION              1024
#define IDC_FAN2_EDIT                   1024
#define IDC_NEG_12V_2_EDIT              1024
#define IDC_CYCLE_TIMES                 1024
#define IDC_STC1                        1024
#define IDC_REFLTEST_LIMIT              1024
#define IDC_CW_EX_EDIT4                 1024
#define IDC_VEL_EX_EDIT2                1024
#define IDC_DRIVER_B                    1025
#define IDC_RADIO_DATA_LEN              1025
#define IDC_DATA_CALL                   1025
#define IDC_FAN3_EDIT                   1025
#define IDC_PA2_TEMP_EDIT               1025
#define IDC_SLOP_TIMES                  1025
#define IDC_STC2                        1025
#define IDC_PL_DC1DIRCOUP               1025
#define IDC_CW_EX_EDIT5                 1025
#define IDC_VEL_EDIT2                   1025
#define IDC_WMO_BLK_NUM                 1026
#define IDC_FAN4_EDIT                   1026
#define IDC_PA3_TEMP_EDIT               1026
#define IDC_STC3                        1026
#define IDC_PL_FC1COAX                  1026
#define IDC_CW_EX_EDIT6                 1026
#define IDC_VEL_EX_EDIT3                1026
#define IDC_EDIT_Ps15v                  1026
#define IDC_OBLIQUE_LOW_TAVG            1027
#define IDC_IDC_GOES_MSG_LEN            1027
#define IDC_STATION_NUM                 1027
#define IDC_FAN5_EDIT                   1027
#define IDC_PA4_TEMP_EDIT               1027
#define IDC_STC4                        1027
#define IDC_PL_FC3HARM                  1027
#define IDC_CW_EX_EDIT7                 1027
#define IDC_VEL_EDIT3                   1027
#define IDC_EDIT_Psm15v                 1027
#define IDC_OBLIQUE_LOW_SAVG            1028
#define IDC_GOES_VER_PARITY             1028
#define IDC_BEAM1_EL                    1028
#define IDC_DOP_BIN_NUM                 1028
#define IDC_FAN6_EDIT                   1028
#define IDC_PA5_TEMP_EDIT               1028
#define IDC_STC5                        1028
#define IDC_PL_UD4ANT                   1028
#define IDC_CW_EX_EDIT8                 1028
#define IDC_VEL_EX_EDIT4                1028
#define IDC_EDIT_Ps9v                   1028
#define IDC_OBLIQUE_HIGH_TAVG           1029
#define IDC_RADIO_DATA_INC              1029
#define IDC_BEAM1_AZ                    1029
#define IDC_FAN7_EDIT                   1029
#define IDC_PA6_TEMP_EDIT               1029
#define IDC_STC6                        1029
#define IDC_PL_2A1A2TR                  1029
#define IDC_CW_EX_EDIT9                 1029
#define IDC_VEL_EDIT4                   1029
#define IDC_EDIT_Ps3_3v                 1029
#define IDC_OBLIQUE_HIGH_SAVG           1030
#define IDC_X_ON_OFF                    1030
#define IDC_LOW_MODE                    1030
#define IDC_BEAM2_EL                    1030
#define IDC_FAN8_EDIT                   1030
#define IDC_PA7_TEMP_EDIT               1030
#define IDC_STC7                        1030
#define IDC_PL_2A1A3LIMITR              1030
#define IDC_CW_EX_EDIT10                1030
#define IDC_WID_EX_EDIT1                1030
#define IDC_EDIT_Ps5v1                  1030
#define IDC_OBLIQUE_LOW_PRT             1031
#define IDC_SUBMODE                     1031
#define IDC_BEAM3_EL                    1031
#define IDC_PA8_TEMP_EDIT               1031
#define IDC_SPARE_EDIT                  1031
#define IDC_STC8                        1031
#define IDC_PL_2A1A1DIRCOUP             1031
#define IDC_DATASOURCESEL               1031
#define IDC_CW_EX_EDIT11                1031
#define IDC_WID_EDIT1                   1031
#define IDC_EDIT_Ps5v2                  1031
#define IDC_OBLIQUE_HIGH_PRT            1032
#define IDC_SYS_PASSWORD                1032
#define IDC_BEAM4_EL                    1032
#define IDC_DUTY_CYCLE_RATIO_EDIT       1032
#define IDC_STC9                        1032
#define IDC_PL_RFATTEN                  1032
#define IDC_CW_EX_EDIT12                1032
#define IDC_WID_EX_EDIT2                1032
#define IDC_PA9_TEMP_EDIT               1032
#define IDC_VERTICAL_LOW_TAVG           1033
#define IDC_BEAM5_EL                    1033
#define IDC_LOGON_PASSWORD              1033
#define IDC_VSWR_EDIT                   1033
#define IDC_STC10                       1033
#define IDC_PL_2A4A2FOURSWH             1033
#define IDC_CW_EX_EDIT13                1033
#define IDC_WID_EDIT2                   1033
#define IDC_PA10_TEMP_EDIT              1033
#define IDC_EDIT_Ps24v                  1033
#define IDC_VERTICAL_LOW_SAVG           1034
#define IDC_BEAM6_EL                    1034
#define IDC_ARCHIVEA_PATH               1034
#define IDC_AIR_TEMP_EDIT               1034
#define IDC_CURARCH_PATH                1034
#define IDC_STC11                       1034
#define IDC_PL_2A4A5FIXATTEN            1034
#define IDC_6MINCURARCH_PATH            1034
#define IDC_CW_EX_EDIT14                1034
#define IDC_WID_EX_EDIT3                1034
#define IDC_EDIT_Ps12v                  1034
#define IDC_VERTICAL_HIGH_TAVG          1035
#define IDC_BEAM2_AZ                    1035
#define IDC_LR_SWITCH_EDIT              1035
#define IDC_STC12                       1035
#define IDC_PL_DELAYLIN                 1035
#define IDC_CW_EX_EDIT15                1035
#define IDC_WID_EDIT3                   1035
#define IDC_EDIT_Ps6v                   1035
#define IDC_VERTICAL_HIGH_SAVG          1036
#define IDC_BEAM3_AZ                    1036
#define IDC_MODULE_FAULT_SUMMARY_EDIT   1036
#define IDC_STC13                       1036
#define IDC_CW_2A4A2J3                  1036
#define IDC_CW_EX_EDIT16                1036
#define IDC_WID_EX_EDIT4                1036
#define IDC_EDIT_Ps5v3                  1036
#define IDC_VERTICAL_LOW_PRT            1037
#define IDC_BEAM4_AZ                    1037
#define IDC_DRIVER_FAULT_SUMMARY_EDIT   1037
#define IDC_STC14                       1037
#define IDC_PL_FC2CIRCULATOR            1037
#define IDC_CW_EX_EDIT17                1037
#define IDC_WID_EDIT4                   1037
#define IDC_EDIT_Ps5v4                  1037
#define IDC_VERTICAL_HIGH_PRT           1038
#define IDC_BEAM5_AZ                    1038
#define IDC_SYSTEM_FAULT_SUMMARY_EDIT   1038
#define IDC_STC15                       1038
#define IDC_ANT_GAIN                    1038
#define IDC_EDIT_Psm5v                  1038
#define IDC_RANGBIN_LIST                1039
#define IDC_BEAM6_AZ                    1039
#define IDC_HPA1_STATUS_EDIT            1039
#define IDC_STC16                       1039
#define IDC_ANT_BMWID                   1039
#define IDC_ANT_VERBMWID                1039
#define IDC_EDIT_Tx_Input               1039
#define IDC_EAST                        1040
#define IDC_HPA2_STATUS_EDIT            1040
#define IDC_STC17                       1040
#define IDC_RFDRIVE_2A4A2J2             1040
#define IDC_EDIT_Tx_Output              1040
#define IDC_NORTH                       1041
#define IDC_HPA3_STATUS_EDIT            1041
#define IDC_STC18                       1041
#define IDC_NOISE_2A4A2J4               1041
#define IDC_EDIT_Tx_Reflect             1041
#define IDC_VERTICAL                    1042
#define IDC_HPA4_STATUS_EDIT            1042
#define IDC_STC19                       1042
#define IDC_EDIT_Tx_Temp                1042
#define IDC_COMBO_FFT                   1043
#define IDC_HPA5_STATUS_EDIT            1043
#define IDC_STC20                       1043
#define IDC_OBLIQUE_LOW_PW              1044
#define IDC_HPA6_STATUS_EDIT            1044
#define IDC_STC21                       1044
#define IDC_CHECK_DRIVER_A              1044
#define IDC_VERTICAL_LOW_PW             1045
#define IDC_HPA7_STATUS_EDIT            1045
#define IDC_STC22                       1045
#define IDC_CHECK_DRIVER_B              1045
#define IDC_OBLIQUE_HIGH_PW             1046
#define IDC_HPA8_STATUS_EDIT            1046
#define IDC_STC23                       1046
#define IDC_BEAM                        1046
#define IDC_VERTICAL_HIGH_PW            1047
#define IDC_HPA9_STATUS_EDIT            1047
#define IDC_STC24                       1047
#define IDC_TIMEDOMAINBT                1047
#define IDC_HPA10_STATUS_EDIT           1048
#define IDC_PLSWID_V                    1048
#define IDC_PLSWID_HIGH                 1048
#define IDC_FREQDOMAINBT                1048
#define IDC_WEST                        1048
#define IDC_HPA1_PWR_EDIT               1049
#define IDC_PLSWID_O                    1049
#define IDC_PLSWID_LOW                  1049
#define IDC_SLIDER                      1049
#define IDC_SOUTH                       1049
#define IDC_HPA2_PWR_EDIT               1050
#define IDC_RFD1_EDIT                   1050
#define IDC_RFATTEN_VALUE               1050
#define IDC_COMBO_PSC                   1050
#define IDC_HPA3_PWR_EDIT               1051
#define IDC_RFD2_EDIT                   1051
#define IDC_RTACSLIDER                  1051
#define IDC_HPA4_PWR_EDIT               1052
#define IDC_RFD3_EDIT                   1052
#define IDC_LIST                        1052
#define IDC_HPA5_PWR_EDIT               1053
#define IDC_VELOCITY2_EDIT              1053
#define IDC_FIGURE                      1053
#define IDC_HPA6_PWR_EDIT               1054
#define IDC_VELOCITY3_EDIT              1054
#define IDC_RTAC_VALUE                  1054
#define IDC_HPA7_PWR_EDIT               1055
#define IDC_VELOCITY4_EDIT              1055
#define IDC_INTRCOUNT                   1055
#define IDC_HPA8_PWR_EDIT               1056
#define IDC_WIDTH2_EDIT                 1056
#define IDC_SWEEPNUM                    1056
#define IDC_HPA9_PWR_EDIT               1057
#define IDC_WIDTH3_EDIT                 1057
#define IDC_FFTPOINTS                   1057
#define IDC_HPA10_PWR_EDIT              1058
#define IDC_WIDTH4_EDIT                 1058
#define IDC_PRT                         1058
#define IDC_PA1_TEMP_EDIT               1059
#define IDC_RFD3_EX_EDIT                1059
#define IDC_BSU_FAULT_EDIT              1060
#define IDC_RFD1_EX_EDIT                1060
#define IDC_SHAREDMEMORY                1060
#define IDC_VSWR_FAULT_EDIT             1061
#define IDC_RFD2_EX_EDIT                1061
#define IDC_TCPIP                       1061
#define IDC_HPA0_STATUS                 1061
#define IDC_FORWARDED_POWER_EDIT        1062
#define IDC_UDP                         1062
#define IDC_HPA1_STATUS                 1062
#define IDC_HPA0_STATUS2                1062
#define IDC_REFLECTED_POWER_EDIT        1063
#define IDC_NONE                        1063
#define IDC_HPA2_STATUS                 1063
#define IDC_HPA0_STATUS3                1063
#define IDC_RF_TEST_SIGNAL_EDIT         1064
#define IDC_HPA3_STATUS                 1064
#define IDC_HPA0_STATUS4                1064
#define IDC_AD_CLOCK_EDIT               1065
#define IDC_HPA4_STATUS                 1065
#define IDC_HPA0_STATUS5                1065
#define IDC_LO_SAMPLE_EDIT              1066
#define IDC_HPA5_STATUS                 1066
#define IDC_DOOR_SWITCH_EDIT            1067
#define IDC_HPA6_STATUS                 1067
#define IDC_INSIDE_TEMP_EDIT            1068
#define IDC_HPA7_STATUS                 1068
#define IDC_OUTSIDE_TEMP_EDIT           1069
#define IDC_HPA8_STATUS                 1069
#define IDC_SPS_STATUS_EDIT             1070
#define IDC_HPA9_STATUS                 1070
#define IDC_PS_6V3A_EDIT                1071
#define IDC_WHOLERANGE                  1071
#define IDC_PS_6V2p5A_EDIT              1072
#define IDC_IF_CLOCK_EDIT               1073
#define IDC_PULSECOMPRESS               1073
#define IDC_DDC_EDIT                    1074
#define IDC_SPARE_EDIT1                 1075
#define IDC_ANTENNADUMYLOAD_EDIT        1075
#define IDC_HIGHMODETOGGLE              1075
#define IDC_POS_12V_1_EDIT              1076
#define IDC_RFD_EDIT                    1076
#define IDC_POS_12V_2_EDIT              1077
#define IDC_PATHBINARY                  1077
#define IDC_25M_CW_EDIT                 1077
#define IDC_POS_28V_1_EDIT              1078
#define IDC_PATHTEXT                    1078
#define IDC_POS_28V_2_EDIT              1079
#define IDC_CYCLETEST                   1079
#define IDC_POS_40V_1_EDIT              1080
#define IDC_REMOTECTRL                  1080
#define IDC_POS_40V_2_EDIT              1081
#define IDC_POS_40V_3_EDIT              1082
#define IDC_SPARE_EDIT2                 1083
#define IDC_SPARE_EDIT3                 1084
#define IDC_ADVANCEDSET_LIST            1084
#define IDC_NEG_5V_1_EDIT               1085
#define IDC_OPEN                        1085
#define IDC_NEG_5V_2_EDIT               1086
#define IDC_LOWMODEDMA_SLIDER           1086
#define IDC_POS_5V_1_EDIT               1087
#define IDC_HIGHMODEDMA_SLIDER          1087
#define IDC_POS_5V_2_EDIT               1088
#define IDC_NEG_12V_1_EDIT              1089
#define IDC_HIGHMODE240                 1089
#define IDC_DRV_RF_OUTPUT_POWER_EDIT    1090
#define IDC_SYSTEM_FORWARD_POWER_EDIT   1091
#define IDC_CAB_OUTLET_AIR_TEMP_EDIT    1092
#define IDC_DONOTREPORT                 1092
#define IDC_25M_SIG_CLOSE               1092
#define IDC_CAB_INLET_AIR_TEMP_EDIT     1093
#define IDC_SM_INUSE                    1093
#define IDC_ALARMLIST                   1093
#define IDC_DRV_MODULE1_TEMP_EDIT       1094
#define IDC_GM_INUSE                    1094
#define IDC_STATIC_Tx5v                 1094
#define IDC_DRV_MODULE2_TEMP_EDIT       1095
#define IDC_STATIC_Tx13v                1095
#define IDC_STATIC_BATTERY_LOW          1095
#define IDC_PORTCOMBO                   1096
#define IDC_STATIC_Tx50v                1096
#define IDC_STATIC_BYPASSBOOST          1096
#define IDC_BAUDCOMBO                   1097
#define IDC_STATIC_Tx28v                1097
#define IDC_BYTESIZE                    1098
#define IDC_STATIC_Tx36v                1098
#define IDC_STATIC_UPS_FAIL             1098
#define IDC_PARITYCOMBO                 1099
#define IDC_STATIC_Tx15v                1099
#define IDC_STATIC_ONLINE               1099
#define IDC_STOPBITS                    1100
#define IDC_STATIC_Txm15v               1100
#define IDC_STATIC_TEST_IN_PROGRESS     1100
#define IDC_PORTCOMBO_GM                1101
#define IDC_STATIC_Ps15v                1101
#define IDC_STATIC_SHUT_DOWN_ACTIVE     1101
#define IDC_BAUDCOMBO_GM                1102
#define IDC_STATIC_Psm15v               1102
#define IDC_BYTESIZE_GM                 1103
#define IDC_STATIC_Ps9v                 1103
#define IDC_PARITYCOMBO_GM              1104
#define IDC_STATIC_Ps3_3v               1104
#define IDC_STOPBITS_GM                 1105
#define IDC_STATIC_Ps5v1                1105
#define IDC_STATIC_Ps24v                1106
#define IDC_STATIC_Ps12v                1107
#define IDC_STATIC_Ps6v                 1108
#define IDC_STATIC_Ps5v3                1109
#define IDC_STATIC_Ps5v4                1110
#define IDC_STATIC_Psm5v                1111
#define IDC_STATIC_Ps5v2                1112
#define IDC_STATIC_SP                   1113
#define IDC_STATIC_SW                   1114
#define IDC_STATIC_OUTPUT               1115
#define IDC_STATIC_OVERTEMP             1116
#define IDC_STATIC_RF                   1117
#define IDC_STATIC_RF_FAULT             1118
#define IDC_SPIN2                       1120
#define IDC_SPIN                        1120
#define IDC_SPIN3                       1121
#define IDC_STATIC_WAVCC                1123
#define IDC_STATIC_WDVCC                1124
#define IDC_STATIC_WIQCLK               1125
#define IDC_STATIC_WAVCC2               1126
#define IDC_STATIC_TX_INPUT             1126
#define IDC_STATIC_WDVCC2               1127
#define IDC_STATIC_TX_SWR               1127
#define IDC_STATIC_WDVCC3               1128
#define IDC_STATIC_TX_PS                1128
#define IDC_STATIC_T0                   1131
#define IDC_STATIC_LRB                  1132
#define IDC_STATIC_RD                   1133
#define IDC_STATIC_WADCLK               1134
#define IDC_STATIC_SPBSUFLT             1135
#define IDC_BUTTON_UPS                  1136
#define IDC_BUTTON_STATUS               1137
#define IDC_STATIC_UTILITY_FAIL         1138
#define IDC_STATIC_LRB2                 1138
#define IDC_STATIC_TX_OUTPUT            1138
#define IDC_STATIC_RD2                  1139
#define IDC_STATIC_TX_OVERTEMP          1139
#define IDC_CUSTOM1                     1140
#define IDC_STATIC_RD3                  1140
#define IDC_STATIC_TX_RFON              1140
#define IDC_STATIC_TRAMP                1141
#define IDC_CHECK_NORTH                 1142
#define IDC_CHECK_VIRTICAL              1143
#define IDC_CHECK_SOUTH                 1144
#define IDC_CHECK_WEST                  1145
#define IDC_CHECK_EAST                  1146
#define IDC_STATIC_STC                  1147
#define IDC_COMBO1                      1148
#define IDC_COMBO_WINDOW                1148
#define IDC_STATIC_TXBIAS               1148
#define IDC_CHECK6                      1150
#define IDC_STATIC_INPUT_PWR            1154
#define IDC_STATIC_DUTY                 1155
#define IDC_LIST_SM_LIST                1155
#define IDC_STATIC_OUTPUT_PWR           1156
#define IDC_IPADDRESS                   1156
#define IDC_CHECK1                      1171
#define IDC_CHECK_IDATA                 1171
#define IDC_CHECK_SAVE_RESULTS          1171
#define IDC_CHECK_IQREVERSE             1171
#define IDC_SM_HRD_CHECK                1171
#define IDC_CHECK2                      1172
#define IDC_CHECK_QDATA                 1172
#define IDC_CHECK_SAVE_DETAILS          1172
#define IDC_CHECK_DCREMOVAL             1172
#define IDC_GM_HRD_CHECK                1172
#define IDC_CHECK3                      1173
#define IDC_CHECK_SAMP                  1173
#define IDC_CHECK_RAW_CONTROL           1173
#define IDC_CHECK4                      1174
#define IDC_CHECK_NUM                   1174
#define IDC_CHECK5                      1175
#define IDC_CHECK_SPEC_SINGLE           1175
#define IDC_CHECK7                      1176
#define IDC_EDIT_EAST                   1176
#define IDC_CHECK_SPEC_AVG              1176
#define IDC_EDIT_NORTH                  1177
#define IDC_CHECK_PEAK_S                1177
#define IDC_STATIC_TIME_SERIES_DISPLAY  1178
#define IDC_CHECK_PEAK_A                1178
#define IDC_BUTTON_ZOOMIN               1179
#define IDC_CHECK_NOISELEVEL            1179
#define IDC_BUTTON_ZOOMOUT              1180
#define IDC_TAB                         1181
#define IDI_ICON141                     1183
#define IDI_ICON151                     1184
#define IDI_ICON161                     1185
#define IDC_LIST1                       1185
#define IDC_LIST_DAT                    1185
#define IDC_LIST_ALARMSHOW              1185
#define IDC_EDIT_FOCUS_RANGBIN          1191
#define IDC_EDIT_SWEEP_START            1192
#define IDC_EDIT_SWEEP_NUM              1193
#define IDC_EDIT_MARKER_POWER           1194
#define IDC_EDIT_MARKER_VELOCITY        1195
#define IDC_EDIT_MARKER_PEAK            1195
#define IDC_PROGRESS_SPEC               1196
#define IDC_EDIT_CHECKER                1197
#define IDC_EDIT_NOISE_LEVEL            1198
#define IDC_SLIDER2                     1203
#define IDC_SLIDER_MARKER               1203
#define IDC_SLIDER_RFGATEMOV            1203
#define IDC_SLIDER3                     1204
#define IDC_SLIDER_PCCODE_MOV           1204
#define IDC_SLIDER4                     1205
#define IDC_SLIDER_BEGINGATE_H          1205
#define IDC_SCROLLBAR1                  1206
#define IDC_SLIDER_RFGATEMOV_L          1206
#define IDC_SCROLLBAR2                  1207
#define IDC_SLIDER5                     1208
#define IDC_SLIDER_BEGINGATE_L          1208
#define IDC_SCROLLBAR3                  1209
#define IDC_SCROLLBAR4                  1210
#define IDC_BUTTON1                     1211
#define IDC_EDIT_WARNNING_NUM           1212
#define IDC_BUTTON2                     1213
#define IDC_BUTTON_INCLINOMETER         1213
#define IDC_SPIN_RFGATE                 1214
#define IDC_SPIN_PCCODE                 1215
#define IDC_SPIN_BEGINGATE_H            1216
#define IDC_SPIN_BEGINGATE_L            1217
#define IDC_EDIT_PCCODE                 1218
#define IDC_SPIN_RFGATE_L               1219
#define IDC_BUTTON_DYNTEST              1222
#define IDC_SPECTRAS_PANE               1223
#define IDC_STATIC_SM_DATA              1225
#define IDM_STARTSAMPLE                 32771
#define ID_SEND_LANDLINE_TEST_MSG       32771
#define IDM_STOPSAMPLE                  32772
#define ID_DOPPLER_TEST                 32772
#define IDM_EXIT                        32773
#define ID_SINGLE_CYCLE_TEST            32773
#define ID_BUTTON32774                  32774
#define ID_RASS_TEST                    32774
#define ID_ID_COMBOBOX                  32774
#define ID_ZEROS                        32774
#define IDM_BASIC_SETTING               32775
#define IDM_NORTEST_SETTING             32776
#define ID_OPERATION                    32776
#define ID_MAINTENANCE                  32777
#define IDM_SIMULATOR                   32778
#define ID_STANDBY                      32778
#define ID_OFFLINE                      32778
#define IDM_SM                          32779
#define ID_RESTART                      32779
#define ID_SYSTEM_PARAM                 32780
#define IDM_STOP_SM                     32781
#define ID_ARCHIVEA                     32781
#define IDM_VELOCITYVARIANCE            32782
#define IDM_TEST_STOP                   32782
#define IDM_SPECTRA                     32783
#define IDM_TEST_START                  32783
#define IDM_SIGNALPOWER                 32784
#define IDM_TESTANDGETDATA              32784
#define IDM_MEANVELOCITY                32785
#define IDM_START_SM                    32786
#define ID_EXIT                         32787
#define IDM_PERFORMANCE                 32788
#define IDM_ADVANCED_SETTING            32788
#define ID_PLAYBACK                     32789
#define IDM_START_UPS                   32789
#define ID_IQSTORE                      32790
#define IDM_STOP_UPS                    32790
#define ID_CONN_IP_SET                  32791
#define ID_RAWIQDATA                    32792
#define IDM_TIME_SERIES                 32792
#define ID_6MINDATA                     32793
#define ID_ARCHIVE_IQDATA               32794
#define IDM_DATAVIEW                    32794
#define ID_ARCHIVE_6MINDATA             32795
#define IDM_TOTALSPEC_VIEW              32795
#define ID_ZERO                         32798
#define ID_ZOOMIN                       32799
#define ID_ZOOMOUT                      32800
#define ID_INDICATOR_DATE               61446
#define ID_INDICATOR_TIME               61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        254
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1226
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
